all: compile run
	@echo No errors

compile:
	kotlinc collections.kt -include-runtime -d collections.jar

run:
	java -jar collections.jar Obst
	java -jar collections.jar Bauteile
	java -jar collections.jar Roboter
