all:
	${MAKE} -C hello-world
	${MAKE} -C sum
	${MAKE} -C string-template
	${MAKE} -C cond-expr
	${MAKE} -C main-args
	${MAKE} -C for-loop
	${MAKE} -C when-expr
	${MAKE} -C ranges
	${MAKE} -C collections
	@echo No errors
